# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

    steps:
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pytest -v --cov=calculator